version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE_KAFKA
      KAFKA_LISTENER_INTERFACE: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_INSIDE_KAFKA: INSIDE_KAFKA
      KAFKA_LISTENER_INSIDE_KAFKA_PORT: 9093
      KAFKA_LISTENER_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      KAFKA_LISTENER_INTERNAL_PORT: 9093
    expose:
      - "9093"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
